name: meteo
version: '0.9.9.1'
summary: Know the forecast of the next hours and days, with data and maps
description: |
  Current weather, with information about temperature, pressure, wind
  speed and direction, sunrise and sunset. Show awesome maps with all
  this information.
grade: stable
base: core20
confinement: strict
architectures: [amd64]
  
slots:
  dbus-meteo:
    interface: dbus
    bus: session
    name: com.gitlab.bitseater.meteo

plugs:
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/share/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/share/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/share/sounds

apps:
  meteo:
    command: bin/desktop-launch $SNAP/usr/bin/com.gitlab.bitseater.meteo
    common-id: com.gitlab.bitseater.meteo
    slots: [ dbus-meteo ]
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - browser-support
      - locale-control
      - gsettings
      - pulseaudio
      - network
      - opengl
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      DISABLE_WAYLAND: 1
      SNAP_DESKTOP_RUNTIME: $SNAP/data-dir/gnome-platform
      GTK_USE_PORTAL: '1'
      XDG_DATA_HOME: usr/share
    desktop: usr/share/applications/com.gitlab.bitseater.meteo.desktop

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  meteo-app:
    after: [desktop-gnome-platform]
    source: https://gitlab.com/bitseater/meteo/-/archive/0.9.9.1/meteo-0.9.9.1.tar.gz
    source-type: tar
    plugin: meson
    meson-parameters: [--prefix=/usr]
    build-packages:
      - gettext
      - appstream
      - desktop-file-utils
      - valac
      - libjson-glib-dev
      - debhelper
      - libsoup2.4-dev
      - libwebkit2gtk-4.0-dev
      - libayatana-appindicator3-dev
      - gsettings-desktop-schemas-dev
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libayatana-appindicator3-1
      - gsettings-desktop-schemas
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=com.gitlab.bitseater.meteo|Icon=/usr/share/icons/hicolor/256x256/apps/com.gitlab.bitseater.meteo\.svg|' usr/share/applications/com.gitlab.bitseater.meteo.desktop

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
